# Copyright The Notary Project Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: dev-release

on:
  schedule:
    - cron: '0 16 * * 0'  # at 16:00 on Sunday (UTC)
  workflow_dispatch:

jobs:
  build:
    name: Weekly Release Notation Binaries
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: ['1.20']
      fail-fast: true
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Set Git User
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Create Version Tag
        run: |
          # get project version: <SemVer>.dev.<YYYYMMDD>
          export TAG_VERSION=`cat ./internal/version/version.go | grep "Version = " | awk -F '"' '{print $2}'`.dev.`date +%Y%m%d`

          # create new tag
          git tag -af $TAG_VERSION -m "For weekly build"
          git push origin $TAG_VERSION
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # v4.3.0
        with:
          distribution: goreleaser
          version: latest
          args: release -f ./.dev.goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete old dev release
        uses: dev-drprasad/delete-older-releases@653dc03d96473ac9e585c68c8bf5aaccb0dadb61 # v0.2.1
        with:
          keep_latest: 1
          delete_tag_pattern: ".dev."
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
